### ISSUE TITLE
HW Section Overflow

### ISSUE THREAD

**Issue by willbarkoff** [ULTIMATHEXERS/DaltonTab#11] opened 2016-01-04 21:57 UTC
![yay](https://cloud.githubusercontent.com/assets/10969136/12101694/151f283c-b304-11e5-91d0-348549295fed.png)

**Comment by thatoddmailbox** [comment] 2016-01-04 21:59
@nywillb This is a duplicate of #10 and has been fixed in the latest version, pushed to the Chrome Web Store about an hour ago. Make sure you've synced (if using git repo) or done a force update from the Chrome extensions page.

**Closed as completed by thatoddmailbox** 2016-01-04 21:59 UTC
